/*
 * modbus_protocol.c
 *
 *  Created on: Jul 5, 2026
 *      Author: tomas
 */

/**
 * @file modbus_protocol.c
 *
 * @brief Modbus RTU protocol logic independent of the STM32 hardware.
 *
 * This module contains functions that operate only on raw Modbus frames.
 * It does not know anything about UART, DMA, GPIO, FreeRTOS or the RS-485
 * transceiver.
 *
 * Keeping protocol parsing separate from the hardware layer makes the code
 * easier to test and reason about. The same validation logic could also be
 * reused with a different UART driver or even on a different MCU.
 */

#include <stdint.h>
#include "modbus_protocol.h"

/**
 * @brief Calculate CRC16 according to the Modbus RTU specification.
 *
 * Modbus RTU appends a 16-bit CRC to every frame. The receiver calculates
 * the CRC again and compares it with the CRC received from the slave.
 *
 * The algorithm starts with 0xFFFF and processes every byte bit-by-bit.
 * Modbus uses the polynomial 0xA001 and processes the least significant bit
 * first.
 *
 * Important: this function only calculates the CRC. It does not append it
 * to the buffer or modify the input data.
 *
 * @param data Pointer to the bytes for which the CRC should be calculated.
 * @param len Number of bytes to process.
 *
 * @return Calculated Modbus CRC16 value.
 */
uint16_t modbus_crc16(const uint8_t *data, uint16_t len) {
	uint16_t crc = 0xFFFF;

	/*
	 * Process every byte of the input buffer.
	 */
	for (uint16_t byte_index = 0; byte_index < len; byte_index++) {
		crc ^= (uint16_t) data[byte_index];

		/*
		 * Each byte is processed one bit at a time.
		 *
		 * The least significant bit is checked first because Modbus CRC
		 * uses LSB-first processing.
		 */
		for (uint8_t i = 0; i < 8; i++) {

			if (crc & 0x0001) {

				/*
				 * If the lowest bit is set, shift right and apply the
				 * Modbus polynomial.
				 */
				crc >>= 1;
				crc ^= 0xA001;

			} else {

				/*
				 * If the lowest bit is not set, only the shift is needed.
				 */
				crc >>= 1;
			}
		}
	}

	return crc;
}

/**
 * @brief Validate a received Modbus response frame.
 *
 * The function checks the frame in a deliberate order:
 *
 * 1. Basic length check.
 * 2. Slave address.
 * 3. CRC.
 * 4. Exception response.
 * 5. Expected function code.
 * 6. Expected total frame length.
 *
 * CRC is checked before interpreting the remaining fields because until
 * frame integrity is confirmed, none of the other bytes should be trusted.
 *
 * @param modbus_rx_buffer Received Modbus frame.
 * @param size Number of bytes received.
 * @param slave_id Expected slave address.
 * @param function_code Expected Modbus function code.
 * @param register_count Number of registers expected in the response.
 *
 * @return
 *         MODBUS_OK               Frame is valid.
 *         MODBUS_ERR_LENGTH       Frame length is invalid.
 *         MODBUS_ERR_ADDRESS      Response came from an unexpected slave.
 *         MODBUS_ERR_CRC          CRC verification failed.
 *         MODBUS_ERR_EXCEPTION    Slave returned an exception or an
 *                                 unexpected function code.
 */
ModbusStatus_t modbus_validate_frame(const uint8_t *modbus_rx_buffer,
		uint16_t size, uint8_t slave_id, uint8_t function_code,
		uint8_t register_count) {

	/*
	 * The shortest possible Modbus RTU response contains:
	 *
	 *   address + function + CRC(2 bytes)
	 *
	 * Therefore anything shorter than 4 bytes cannot be a valid response.
	 */
	if (size < 4) {
		return MODBUS_ERR_LENGTH;
	}

	/*
	 * Verify that the response came from the slave we actually queried.
	 *
	 * This prevents us from accepting a valid frame generated by another
	 * device on the same RS-485 bus.
	 */
	if (slave_id != modbus_rx_buffer[0]) {
		return MODBUS_ERR_ADDRESS;
	}

	/*
	 * The last two bytes contain the CRC sent by the slave.
	 * The CRC calculation itself covers all preceding bytes.
	 */
	uint16_t crc = modbus_crc16(modbus_rx_buffer, size - 2);

	uint16_t received_crc = modbus_rx_buffer[size - 2]
			| (modbus_rx_buffer[size - 1] << 8);

	if (crc != received_crc) {
		return MODBUS_ERR_CRC;
	}

	/*
	 * In Modbus, a response with bit 7 of the function code set indicates
	 * an exception response.
	 *
	 * Example:
	 * normal function code 0x03
	 * exception response  0x83
	 *
	 * We treat this as a logical protocol error rather than a transmission
	 * error, so the caller will not retry the same request.
	 */
	if (modbus_rx_buffer[1] >= 0x80) {
		return MODBUS_ERR_EXCEPTION;
	}

	/*
	 * The response must correspond to the function code we requested.
	 * At this point the CRC has already been verified, so the field can be
	 * trusted.
	 */
	if (modbus_rx_buffer[1] != function_code) {
		return MODBUS_ERR_EXCEPTION;
	}

	/*
	 * For a Read Holding Registers response (function 0x03), each register
	 * contributes 2 data bytes.
	 *
	 * Total frame length is:
	 *
	 *   address      1 byte
	 *   function     1 byte
	 *   byte count   1 byte
	 *   data         2 * register_count bytes
	 *   CRC          2 bytes
	 */
	uint8_t expected_length = 5 + (2 * register_count);

	if (size != expected_length) {
		return MODBUS_ERR_LENGTH;
	}

	return MODBUS_OK;
}
