/*
 * modbus_master.h
 *
 *  Created on: Jul 11, 2026
 *      Author: tomas
 */

#ifndef INC_MODBUS_MASTER_H_
#define INC_MODBUS_MASTER_H_

#include "modbus_protocol.h"
#include "usart.h"

/**
 * @brief Configuration of the Modbus device being queried.
 *
 * Fields map directly onto the request frame bytes.
 */
typedef struct {
	uint8_t slave_id;
	uint8_t function_code;
	uint8_t register_start_hi;
	uint8_t register_start_lo;
	uint8_t register_count_hi;
	uint8_t register_count_lo;
} ModbusTarget_t;

/**
 * @brief Timing and retry configuration for Modbus communication.
 *
 * A retry is used for communication-level problems (timeout, CRC error,
 * malformed frame). A valid Modbus exception response is a logical answer
 * from the slave and is not retried.
 */
typedef struct {
	uint16_t poll_period_ms;
	uint16_t response_timeout_ms;
	uint8_t max_attempts;
} ModbusRetryPolicy_t;

/**
 * @brief Start UART reception for Modbus responses using DMA + IDLE detection.
 */
ModbusStatus_t modbus_master_init(void);

/**
 * @brief Execute one Modbus request/response transaction.
 *
 * Sends the request, waits for a response, validates it and retries when
 * the error is retryable. modbus_rx_data is only valid when the return
 * value is MODBUS_OK.
 */
ModbusStatus_t modbus_master_poll(
		uint8_t *modbus_tx_buffer,
		uint8_t modbus_tx_buffer_size,
		uint8_t *modbus_rx_data,
		const ModbusTarget_t *modbus_target,
		const ModbusRetryPolicy_t *modbus_retry_policy);

/**
 * @brief Handle a UART reception event generated by ReceiveToIdle_DMA.
 *
 * Stores the received frame size, marks the buffer ready and re-arms DMA
 * reception. Validation happens later, from task context.
 */
void modbus_rx_event(
		HAL_UART_RxEventTypeTypeDef event,
		uint16_t Size);

#endif /* INC_MODBUS_MASTER_H_ */
